# yaml-language-server: $schema=./node_modules/envio/fuel.schema.json
name: envio-indexer
ecosystem: fuel
networks:
  - id: 0
    start_block: 0
    hyperfuel_config:
      url: https://mainnet2.hypersync.xyz
    contracts:
      - name: Diesel
        address:
          - 0x35c869e31e29f1e659990a4f02a0a2cf9d3ee6c4e6a4ce9ed8a4f589daa125c6
        abi_file_path: abis/mainnet/diesel-abi.json
        handler: src/EventHandlers.ts
        events:
          - name: MintEvent
          - name: BurnEvent
          - name: CreatePoolEvent
          - name: SwapEvent
raw_events: true
