# yaml-language-server: $schema=./node_modules/envio/fuel.schema.json
name: envio-indexer
ecosystem: fuel
networks:
  - id: 0
    start_block: 0
    hyperfuel_config:
      url: https://mainnet2.hypersync.xyz
    contracts:
      - name: Mira
        address:
          - 0x3f0f8628d6c59d5f78be5e6b573c74d5112f601e367b90763217439225ab4940
        abi_file_path: abis/mainnet/mira-abi.json
        handler: src/EventHandlers.ts
        events:
          - name: MintEvent
          - name: BurnEvent
          - name: CreatePoolEvent
          - name: SwapEvent
raw_events: true
