# yaml-language-server: $schema=./node_modules/envio/fuel.schema.json
name: envio-indexer
ecosystem: fuel
networks:
  - id: 0
    start_block: 0
    hyperfuel_config:
      url: https://mainnet2.hypersync.xyz
    contracts:
      - name: Mira
        address:
          - 0x51bb9bf2f9df6c3af3a52ca0bad250ce12df40f27f8ea542403230bfda987526
        abi_file_path: abis/mainnet/mira-abi.json
        handler: src/EventHandlers.ts
        events:
          - name: MintEvent
          - name: BurnEvent
          - name: CreatePoolEvent
          - name: SwapEvent
raw_events: true
